apiVersion: v1
data:
  health.html: |
    OK
  index.php: |
    <html>
     <head>
      <title>A Simple Microservice</title>
     </head>
     <body>
     <?php echo '<p>Hello World !!!</p>'; ?> 
     </body>
    </html>
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
